# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# main:
#   - name: Home
#     url: /
#     weight: 10
# - name: Blog
#   url: blog/
#   weight: 20
# - name: Uses
#   url: uses/
#   weight: 30

main:
  - name: About
    identifier: about
    url: /#about
    weight: 10
  - name: Research Interests
    identifier: research-interests
    url: /#research-interests
    weight: 20
  - name: Articles
    identifier: articles
    url: /#articles
    weight: 30
  - name: Education
    identifier: education
    url: /#education
    weight: 40
  - name: Experience
    identifier: experience
    url: /#experience
    weight: 50
