hugoblox:
  schema: "2.0"
  identity:
    name: Matthias Allard
    type: person
    tagline: Researcher
    description: researcher
  theme:
    mode: system
    pack: coffee
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
    pack: academic
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
    cta:
      enable: false
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
    license:
      share_alike: true
  content:
    math:
      enable: true
    toc:
      enable: true
    reading_time:
      enable: false
    citations:
      style: apa
  search:
    enable: true
  pro:
    hide_attribution: false
